### ISSUE TITLE
Regarding the question and answer generation project

### ISSUE THREAD

**Issue by Phani194** [holylovenia/question-answer-generation#1]
I am facing an error while the program is executed  like to set the environment variable,and NLTK is unable to find the Stanford parser,can any one explain to solve this issue
![IMG_20191015_143433](https://user-images.githubusercontent.com/56482888/66951299-b205a680-f077-11e9-92c0-88a03a174084.jpg)

**Comment by holylovenia** [comment]
We used PCFG Stanford Parser from [this link](https://nlp.stanford.edu/software/lex-parser.shtml).

**Comment by Phani194** [comment]
I am getting an error during the execution ,is there any video about your
project execution how to do it

**Comment by Phani194** [comment]
can you add the requirements.txt file for this project

**Comment by aravindchaluvadi** [comment]
IN UBUNTU:

Even if i download the file and add in classpath iam still getting the same error  can someone help me in this
![Screenshot from 2019-11-26 15-20-14]

(https://user-images.githubusercontent.com/25568301/69618762-6e339300-1060-11ea-9f1d-b509b84f9d8d.png)

**Comment by agusgun** [comment]
Hello @Phani194 @aravindchaluvadi, thanks for the report. I will work on this issue

**Comment by agusgun** [comment]
Hello I have pushed the new commit, please try it once again. Thank you!
