### ISSUE TITLE
CLASSPATH STANFORD PARSER ERROR - UBUNTU

### ISSUE THREAD

**Issue by aravindchaluvadi** [holylovenia/question-answer-generation#2]
IN UBUNTU:

Even if i download the file and add in classpath iam still getting the same error can someone help me in this
![Screenshot from 2019-11-26 15-20-14]

(https://user-images.githubusercontent.com/25568301/69618762-6e339300-1060-11ea-9f1d-b509b84f9d8d.png)

**Comment by agusgun** [comment]
Have you tried using absolute path instead of relative path? @aravindchaluvadi

**Comment by agusgun** [comment]
Hello, I have pushed the new commit. Please see README to export the PATH and try it once again. Thank you!
