### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn_crfsuite'

### ISSUE THREAD

**Issue by infact** [holylovenia/question-answer-generation#3]
I am always getting [this error](https://stackoverflow.com/questions/61500923/modulenotfounderror-no-module-named-sklearn-crfsuite) even after I installed sklearn_crfsuite

**Comment by francescovannoni** [comment]
Have you tried with pip install sklearn_crfsuite?

**Comment by s-mandeep** [comment]
Make a virtual environment and then install requirements using requirements.txt, it worked for me!

**Comment by agusgun** [comment]
Yes, please install the requirements from requirements.txt
